services:
  helloworld:
    container_name: helloworld
    image: crccheck/hello-world
    expose:
      - 8000
    networks:
      - network_container_deploy

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - network_container_deploy

networks:
  network_container_deploy:
    driver: bridge;
